name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Validate HTML and CSS
        uses: anishathalye/proof-html@v2 # https://github.com/marketplace/actions/proof-html
        with:
          directory: .
          connect_timeout: 20
          max_concurrency: 1
          timeout: 20
          retries: 1
          check_opengraph: false
          ignore_url_re: |
            ^https://fonts.googleapis.com
            ^https://fonts.gstatic.com
