name: Check Site

on:
  schedule:
    - cron: '0 8 * * *'  # Once per day at 08:00 UTC
  workflow_dispatch:

jobs:
  uptime:
    runs-on: ubuntu-latest

    steps:
    - name: Check if site is up
      run: |
        STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" https://artdev99.github.io)
        if [ "$STATUS" -eq "200" ]; then
          echo "Site is up"
        else
          echo "Site is down"
          exit 1
        fi
